@startuml

package entities {
class Client {
- userID: int
- firstName: String
- lastName: String
- role: String
- email: String
- password: String
- balance: double

+ getUserID(): int
+ getFirstName(): String
+ getLastName(): String
+ getRole(): String
+ getEmail(): String
+ getPassword(): String
+ getBalance(): double
+ setBalance(): double
}

class Admin {
- userID: int
- firstName: String
- lastName: String
- role: String
- email: String
- password: String
- balance: double

+ getUserID(): int
+ getFirstName(): String
+ getLastName(): String
+ getRole(): String
+ getEmail(): String
+ getPassword(): String
+ getBalance(): double
+ setBalance(): double
}

class Base {
- variant: String
- price: double

+ getVariant(): String
+ getPrice(): double
}

class Topping {
- variant: String
- price: double

+ getVariant(): String
+ getPrice(): double
}
}

package config {
class SessionConfig {
+ sessionConfig(): SessionHandler
}

class ThymeleafConfig {
+ templateEngine(): TemplateEngine
}
}

package persistence {
class ConnectionPool {
- instance: ConnectionPool
- ds: HikariDataSource
- LOGGER: Logger

+ getInstance(): ConnectionPool
+ getConnection(): Connection
- createHikariConnectionPool(): HikariDataSource
}

class UserMapper {
+ login(): User
+ createAccount(): boolean
}

class UserMapper {
}

class CupcakeMapper {
}

class BaseMapper{
- cp: ConnectionPool
+ getAllBases(): List<Base>
}

class ToppingMapper{
- cp: ConnectionPool
+ getAllToppings(): List<Topping>
}
}

package controllers {
class AdminController {
- app: Javalin
- connectionPool: ConnectionPool
+ addRoutes(): void
}
class ClientController{
- app: Javalin
- connectionPool: ConnectionPool
+ addRoutes(): void
}
}

package service{
class Calculator(){
}
}

class Main(){
}

@enduml